[package]
name = "rime-wanxiang-slim-installer"
version = "1.2.0"
authors = ["Fidel Yin"]
edition = "2024"
license = "GPL-3.0-or-later"

[dependencies]
anyhow = "1"
tempfile = "3"
strum = { version = "0.28", features = ["derive"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "signal"] }
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls"] }
httpdate = "1"
regex = "1"
semver = "1"
sha2 = "0.10"
chrono = { version = "0.4", default-features = false, features = ["clock"] }
zip = { version = "4", default-features = false, features = ["deflate-flate2-zlib-rs"] }
saphyr = { version = "0.0", default-features = false }
octocrab = "0.54"
inquire = { version = "0.9", default-features = false, features = ["crossterm"] }
indicatif = { version = "0.18", default-features = false, features = ["unicode-width"] }
colored = "3"
termimad = "0.35"

[target.'cfg(unix)'.dependencies]
signal-hook = { version = "0.3", default-features = false }

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = 3
strip = "debuginfo"

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
missing-panics-doc = "allow"
used-underscore-binding = "allow"
too-many-lines = "allow"
similar-names = "allow"
