name: Build

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches-ignore:
      - main
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu
          - os: macos-26-intel
            target: x86_64-apple-darwin
          - os: macos-26
            target: aarch64-apple-darwin
          - os: windows-2025
            target: x86_64-pc-windows-msvc
          - os: windows-11-arm
            target: aarch64-pc-windows-msvc

    env:
      BINARY_NAME: rime-wanxiang-slim-installer-${{ matrix.target }}${{ contains(matrix.target, 'windows') && '.exe' || '' }}

    steps:
      - uses: actions/checkout@v7

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: build-${{ matrix.os }}-${{ matrix.target }}

      - name: Build
        run: cargo build --release --locked --target ${{ matrix.target }}

      - name: Rename binary
        working-directory: target/${{ matrix.target }}/release
        run: |
          mv "rime-wanxiang-slim-installer${{ runner.os == 'Windows' && '.exe' || '' }}" "${BINARY_NAME}"

      - uses: actions/upload-artifact@v7
        with:
          name: rime-wanxiang-slim-installer-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/${{ env.BINARY_NAME }}
          if-no-files-found: error
